SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON

CREATE TABLE [dbo].[TableA] (
	[ID] int,
	[Name] varchar(50) COLLATE Chinese_Taiwan_Stroke_CI_AS
) ON [PRIMARY]
CREATE STATISTICS [_WA_Sys_00000001_22AA2996]
ON [dbo].[TableA] ([ID])