SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON

CREATE TABLE [dbo].[BlockTest] (
	[ID] int NOT NULL,
	[Name] nvarchar(50) COLLATE Chinese_Taiwan_Stroke_CI_AS,
	PRIMARY KEY([ID]) WITH (FILLFACTOR=100) ON [PRIMARY]
) ON [PRIMARY]